"""empty message

Revision ID: 7abdf87f8481
Revises: e75f80a7719a
Create Date: 2024-08-06 13:11:11.311422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abdf87f8481'
down_revision = 'e75f80a7719a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
